# **Section A: Data Structures & Control Structures**

**1. Create a list of 5 integers. Perform and print the result of the following operations:**
append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [12]:
nums = [10, 20, 30, 40, 50]
print("Original list:", nums)

nums.append(60)
print("After append:", nums)

nums.extend([70, 80])
print("After extend:", nums)

nums.insert(2, 25)
print("After insert at index 2:", nums)

nums.remove(25)
print("After remove 25:", nums)

popped = nums.pop()
print("Popped element:", popped , "Remaining list:", nums)

nums_copy = nums.copy()
nums_copy.clear()
print("Cleared list:", nums_copy)

print("Index of 30:", nums.index(30))
print("Count of 20:", nums.count(20))

nums.sort()
print("Sorted list:", nums)

nums.reverse()
print("Reversed list:", nums)


Original list: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert at index 2: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove 25: [10, 20, 30, 40, 50, 60, 70, 80]
Popped element: 80 Remaining list: [10, 20, 30, 40, 50, 60, 70]
Cleared list: []
Index of 30: 2
Count of 20: 1
Sorted list: [10, 20, 30, 40, 50, 60, 70]
Reversed list: [70, 60, 50, 40, 30, 20, 10]


**2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.**

In [13]:
students = ("Alice", "Bob", "Charlie")
print("Original tuple:", students)

# students[1] = "Brevis"  # Uncomment this line to see TypeError
print("Explanation: Tuples are immutable, so we cannot change elements once created.")


Original tuple: ('Alice', 'Bob', 'Charlie')
Explanation: Tuples are immutable, so we cannot change elements once created.


**3. Create a set of integers with some duplicate values. Print the set and explain the output.**

In [14]:
nums_set = {1, 2, 2, 3, 4, 4, 5}
print("Set with duplicates removed:", nums_set)
print("Explanation: Sets automatically remove duplicate values.")


Set with duplicates removed: {1, 2, 3, 4, 5}
Explanation: Sets automatically remove duplicate values.


**4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.**

In [15]:
person = {"name": "John", "age": 25, "city": "New York"}
print("Original dictionary:", person)

person["age"] = 26
person["email"] = "john@example.com"
print("Updated dictionary:", person)


Original dictionary: {'name': 'John', 'age': 25, 'city': 'New York'}
Updated dictionary: {'name': 'John', 'age': 26, 'city': 'New York', 'email': 'john@example.com'}


**5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.**

In [16]:
age = 27
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")


Eligible to vote


**6. Given a 'marks' variable, print the grade:**

- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [17]:
marks = 42
if marks >= 90:
    grade = 'A'
elif 75 <= marks <= 89:
    grade = 'B'
elif 50 <= marks <= 74:
    grade = 'C'
else:
    grade = 'Fail'

print("Marks:", marks, "Grade:", grade)


Marks: 42 Grade: Fail


**7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.**

In [18]:
num = 12
if num > 0:
    if num % 2 == 0:
        print(num, "is positive and even")
    else:
        print(num, "is positive but odd")
elif num == 0:
    print("Number is zero")
else:
    print(num, "is negative")



12 is positive and even


# **Section B: Numpy**

**8. Create: A scalar, 1D array, and 2D array**

In [19]:
import numpy as np

scalar = np.array(5)
print("Scalar:", scalar)

array1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array1d)

array2d = np.arange(10, 70, 10).reshape(2, 3)
print("2D Array (2x3):\n", array2d)


Scalar: 5
1D Array: [1 2 3 4 5]
2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


**9. Generate a 4x4 Numpy array of random integers between 0 and 100.**

In [20]:
rand_array = np.random.randint(0, 100, size=(4, 4))
print("Random 4x4 Array:\n", rand_array)


Random 4x4 Array:
 [[32 47  4 81]
 [44 87 56 77]
 [89  1 27 57]
 [ 4  5 14 21]]


**10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names.**

In [21]:
import pandas as pd

array3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df_from_array = pd.DataFrame(array3x3, columns=['A','B','C'])
print("DataFrame from 2D Array:\n", df_from_array)


DataFrame from 2D Array:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# **Section C: Exploring Pandas**

**11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:**

- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [22]:
data = {
    'Name': ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Helen", "Ivy", "Jack"],
    'Age': [23, 25, 30, 22, 29, 24, 31, 28, 26, 27],
    'City': ["NY", "LA", "SF", "NY", "LA", "SF", "NY", "LA", "SF", "NY"],
    'Salary': [50000, 60000, 55000, 62000, None, 58000, 60000, 59000, 60000, 61000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

print("\nInfo:")
print(df.info())

print("\nDescription:")
print(df.describe())

print("\nSelecting Name and City:")
print(df[['Name','City']])

print("\nDropping City column:")
print(df.drop(columns=['City']))

print("\nFilling missing Salary with mean:")
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print(df)

print("\nRemoving duplicate rows:")
df.drop_duplicates(inplace=True)
print(df)


Original DataFrame:
       Name  Age City   Salary
0    Alice   23   NY  50000.0
1      Bob   25   LA  60000.0
2  Charlie   30   SF  55000.0
3    David   22   NY  62000.0
4      Eve   29   LA      NaN
5    Frank   24   SF  58000.0
6    Grace   31   NY  60000.0
7    Helen   28   LA  59000.0
8      Ivy   26   SF  60000.0
9     Jack   27   NY  61000.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Description:
            Age        Salary
count  10.00000      9.000000
mean   26.50000  58333.333333
std     3.02765   3708.099244
min    22.00000  50000.000000
25%    24.25000  58000.000000
50%    26.50000  60000.000000
75%    28.75000  60000.